import Foundation

struct Person {
    let firstName: String
    let lastName: String?
    let age: Int?
    let profilePicture: URL?
}

extension Person {

    var sortableName: String {
        if let lastName = lastName {
            return lastName
        }
        return firstName
    }
}

extension Array where Element == Person {
    static let allPeople: [Element] = [
        Person(firstName: "Kile",
               lastName: nil,
               age: nil,
               profilePicture: nil),
        Person(firstName: "Christian",
               lastName: nil,
               age: 1,
               profilePicture: URL(string: "https://dummyimage.com/236x233.jpg/ff4444/ffffff")),
        Person(firstName: "Ruttger",
               lastName: nil,
               age: 16,
               profilePicture: URL(string: "https://dummyimage.com/136x162.jpg/5fa2dd/ffffff")),
        Person(firstName: "Eal",
               lastName: "Hartropp",
               age: 24,
               profilePicture: nil),
        Person(firstName: "Michale",
               lastName: "Fever",
               age: 56,
               profilePicture: nil),
        Person(firstName: "Land",
               lastName: "Denizet",
               age: nil,
               profilePicture: URL(string: "https://dummyimage.com/110x212.jpg/cc0000/ffffff")),
        Person(firstName: "Genovera",
               lastName: "Rosie",
               age: 60,
               profilePicture: URL(string: "https://dummyimage.com/181x139.jpg/cc0000/ffffff")),
        Person(firstName: "Emmie",
               lastName: "Walthall",
               age: 2,
               profilePicture: nil),
        Person(firstName: "Lotte",
               lastName: "Liddel",
               age: 74,
               profilePicture: URL(string: "https://dummyimage.com/131x250.jpg/cc0000/ffffff")),
        Person(firstName: "Rice",
               lastName: "Claxson",
               age: 33,
               profilePicture: URL(string: "https://dummyimage.com/173x200.jpg/ff4444/ffffff")),
        Person(firstName: "Nikki",
               lastName: "Rosenblath",
               age: 5,
               profilePicture: URL(string: "https://dummyimage.com/209x168.jpg/cc0000/ffffff")),
        Person(firstName: "Carleen",
               lastName: "MacElroy",
               age: 20,
               profilePicture: URL(string: "https://dummyimage.com/164x209.jpg/cc0000/ffffff")),
        Person(firstName: "Haydon",
               lastName: nil,
               age: 61,
               profilePicture: URL(string: "https://dummyimage.com/199x125.jpg/cc0000/ffffff")),
        Person(firstName: "Legra",
               lastName: "Melmore",
               age: 67,
               profilePicture: URL(string: "https://dummyimage.com/155x170.jpg/5fa2dd/ffffff")),
        Person(firstName: "Pooh",
               lastName: "Ricciardo",
               age: nil,
               profilePicture: URL(string: "https://dummyimage.com/211x227.jpg/5fa2dd/ffffff")),
        Person(firstName: "Saunders",
               lastName: "Wynch",
               age: nil,
               profilePicture: URL(string: "https://dummyimage.com/248x250.jpg/dddddd/000000")),
        Person(firstName: "Fritz",
               lastName: "Ewin",
               age: 97,
               profilePicture: URL(string: "https://dummyimage.com/167x167.jpg/cc0000/ffffff")),
        Person(firstName: "Caryl",
               lastName: "Scoterbosh",
               age: 43,
               profilePicture: URL(string: "https://dummyimage.com/240x201.jpg/dddddd/000000")),
        Person(firstName: "Murry",
               lastName: "Lawlee",
               age: 22,
               profilePicture: URL(string: "https://dummyimage.com/225x182.jpg/ff4444/ffffff")),
        Person(firstName: "Mendel",
               lastName: nil,
               age: 57,
               profilePicture: URL(string: "https://dummyimage.com/238x201.jpg/dddddd/000000")),
        Person(firstName: "Tanny",
               lastName: "Luipold",
               age: 78,
               profilePicture: URL(string: "https://dummyimage.com/237x112.jpg/dddddd/000000")),
        Person(firstName: "Flinn",
               lastName: "Kinde",
               age: 99,
               profilePicture: URL(string: "https://dummyimage.com/116x193.jpg/ff4444/ffffff")),
        Person(firstName: "Carmelle",
               lastName: "Santoro",
               age: nil,
               profilePicture: nil),
        Person(firstName: "Darbee",
               lastName: "Berthon",
               age: 86,
               profilePicture: nil),
        Person(firstName: "Arv",
               lastName: nil,
               age: 8,
               profilePicture: URL(string: "https://dummyimage.com/212x237.jpg/5fa2dd/ffffff")),
        Person(firstName: "Gearalt",
               lastName: "Goodram",
               age: nil,
               profilePicture: nil),
        Person(firstName: "Ludvig",
               lastName: nil,
               age: nil,
               profilePicture: URL(string: "https://dummyimage.com/126x230.jpg/ff4444/ffffff")),
        Person(firstName: "Rosina",
               lastName: nil,
               age: 44,
               profilePicture: URL(string: "https://dummyimage.com/238x228.jpg/dddddd/000000")),
        Person(firstName: "Augusto",
               lastName: nil,
               age: nil,
               profilePicture: URL(string: "https://dummyimage.com/112x174.jpg/ff4444/ffffff")),
        Person(firstName: "Demetris",
               lastName: "Pach",
               age: 91,
               profilePicture: URL(string: "https://dummyimage.com/241x210.jpg/dddddd/000000")),
        Person(firstName: "Vanessa",
               lastName: "Hatherall",
               age: 47,
               profilePicture: nil),
        Person(firstName: "Joanna",
               lastName: "Elsmor",
               age: 56,
               profilePicture: URL(string: "https://dummyimage.com/161x205.jpg/ff4444/ffffff")),
        Person(firstName: "Benedikta",
               lastName: nil,
               age: 67,
               profilePicture: URL(string: "https://dummyimage.com/243x239.jpg/dddddd/000000")),
        Person(firstName: "Sheilakathryn",
               lastName: "Stanger",
               age: 19,
               profilePicture: nil),
        Person(firstName: "Chancey",
               lastName: nil,
               age: 25,
               profilePicture: nil),
        Person(firstName: "Caryn",
               lastName: nil,
               age: 65,
               profilePicture: URL(string: "https://dummyimage.com/190x121.jpg/cc0000/ffffff")),
        Person(firstName: "Hernando",
               lastName: "Haps",
               age: 47,
               profilePicture: nil),
        Person(firstName: "Giordano",
               lastName: "Reidie",
               age: 39,
               profilePicture: URL(string: "https://dummyimage.com/229x153.jpg/5fa2dd/ffffff")),
        Person(firstName: "Town",
               lastName: "McBain",
               age: 78,
               profilePicture: URL(string: "https://dummyimage.com/119x189.jpg/5fa2dd/ffffff")),
        Person(firstName: "Jolynn",
               lastName: "Janecki",
               age: 58,
               profilePicture: URL(string: "https://dummyimage.com/117x143.jpg/5fa2dd/ffffff")),
        Person(firstName: "Albert",
               lastName: "Petegree",
               age: nil,
               profilePicture: nil),
        Person(firstName: "Neila",
               lastName: "Seel",
               age: nil,
               profilePicture: URL(string: "https://dummyimage.com/193x214.jpg/dddddd/000000")),
        Person(firstName: "Jerrie",
               lastName: "Fayerman",
               age: nil,
               profilePicture: nil),
        Person(firstName: "Lon",
               lastName: "Mont",
               age: 15,
               profilePicture: URL(string: "https://dummyimage.com/123x203.jpg/5fa2dd/ffffff")),
        Person(firstName: "Jule",
               lastName: "Beevis",
               age: 50,
               profilePicture: nil),
        Person(firstName: "Mitchell",
               lastName: "Clay",
               age: 56,
               profilePicture: URL(string: "https://dummyimage.com/170x185.jpg/dddddd/000000")),
        Person(firstName: "Karina",
               lastName: "Pidler",
               age: nil,
               profilePicture: nil),
        Person(firstName: "Karalee",
               lastName: "Eldrid",
               age: 7,
               profilePicture: URL(string: "https://dummyimage.com/237x103.jpg/cc0000/ffffff")),
        Person(firstName: "Kirsti",
               lastName: "Quiddinton",
               age: 28,
               profilePicture: URL(string: "https://dummyimage.com/185x215.jpg/ff4444/ffffff")),
        Person(firstName: "Sherlock",
               lastName: "Bennallck",
               age: 31,
               profilePicture: nil)
    ]
}
